const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const schema={title:'선택 규칙 검사',description:'',questions:[{id:'rank',type:'rank',label:'희망 순위',help:'',required:true,rankCount:2,options:['A','B','C']},{id:'checks',type:'checkbox',label:'두 개 선택',help:'',required:true,selectionMode:'exact',selectionCount:2,options:['가','나','다']}]};
const programId='11111111-1111-4111-8111-111111111111';
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/'||/^\/\d+\//.test(p))p='/index.html';const file=path.join(root,p);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[],alerts=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{alerts.push(d.message());await d.accept();});
 await page.route('**/*supabase.co/**',async route=>{let body={};try{body=route.request().postDataJSON()||{};}catch{}
  let data=[];
  if(route.request().url().includes('/functions/'))data=body.action==='public'?{ok:true,program:{id:programId,title:'검사 프로그램'},revision:1,schema}:{ok:true,surveys:[],role:'manager'};
  else if(route.request().url().includes('/auth/'))data={user:null,session:null};
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});
 });
 await page.goto(process.env.NURIM_TEST_URL||('http://127.0.0.1:'+server.address().port));await page.waitForFunction(()=>window.NurimSurvey);
 await page.evaluate(()=>{saveSession({role:'manager',name:'테스트 담당자',accountId:'manager-a',centerName:'기관 A'});applyAdminAccess();document.querySelector('#adminDialog').showModal();resetProgramForm();});
 assert.equal(await page.locator('#centerName').inputValue(),'기관 A');assert(await page.locator('#centerName').evaluate(e=>e.readOnly));
 await page.evaluate(()=>document.querySelector('#programForm').reset());await page.waitForTimeout(50);assert.equal(await page.locator('#centerName').inputValue(),'기관 A');
 await page.evaluate(()=>{saveSession({role:'manager',name:'B',accountId:'manager-b',centerName:'기관 B'});applyAdminAccess();resetProgramForm();});assert.equal(await page.locator('#centerName').inputValue(),'기관 B');
 await page.locator('#programDisabilityTypeOptions input[value="비장애"]').check();assert(await page.locator('#programDisabilityTypeOptions input[value="전체 장애유형"]').isChecked());
 await page.locator('#programDisabilityTypeOptions input[value="발달장애"]').check();assert(!(await page.locator('#programDisabilityTypeOptions input[value="전체 장애유형"]').isChecked()));assert(await page.locator('#programDisabilityTypeOptions input[value="비장애"]').isChecked());
 await page.locator('#programDisabilityTypeOptions input[value="전체 장애유형"]').check();assert(await page.locator('#programDisabilityTypeOptions input[value="비장애"]').isChecked());
 await page.evaluate(()=>{saveSession({role:'super',name:'최고관리자'});applyAdminAccess();});assert(!(await page.locator('#centerName').evaluate(e=>e.readOnly)));
 await page.evaluate(({programId})=>{document.querySelector('#adminDialog').close();window.testProgram=normalizeProgram({...defaultPrograms[0],id:programId,surveyId:'survey-test',consentEnabled:true,consentItems:[{id:'basic',type:'radio',title:'개인정보 동의',text:'테스트',enabled:true}],formEnabled:false,centerName:'기관 A',startDate:'2026-01-01',endDate:'2027-12-31'});openApply(window.testProgram);}, {programId});
 await page.locator('#name').fill('홍길동');await page.locator('#applyDialog').getByLabel('생년월일 연도', {exact:true}).selectOption('2000');await page.locator('#applyDialog').getByLabel('생년월일 월', {exact:true}).selectOption('01');await page.locator('#applyDialog').getByLabel('생년월일 일', {exact:true}).selectOption('01');await page.locator('#phone').fill('01012345678');await page.locator('#type').selectOption({label:'장애 당사자'});await page.locator('#goConsent').click();
 await page.locator('#consentItems input[value="agree"]').check();await page.locator('#signature').fill('다른이름');await page.locator('#applySubmitButton').click();assert(alerts.at(-1).includes('이름과 같아야'));assert(await page.locator('#applyDialog').evaluate(d=>d.open));
 await page.locator('#signature').fill('홍길동');await page.locator('#applySubmitButton').click();
 const frame=page.frameLocator('#nurimSurveyDialog iframe');await frame.locator('h1').waitFor();assert.equal(await frame.locator('[name="answer_rank"]').count(),2);
 await frame.locator('[name="answer_rank"]').nth(0).selectOption('A');await frame.locator('[name="answer_rank"]').nth(1).selectOption('B');await frame.locator('[name="answer_checks"][value="가"]').check();
 await frame.locator('button[type="submit"]').click();assert((await frame.locator('#status').innerText()).includes('2개'));
 await frame.locator('[name="answer_checks"][value="나"]').check();await frame.locator('#previousPage').click();assert(await page.locator('#applyDialog').evaluate(d=>d.open));assert.equal(await page.locator('#name').inputValue(),'홍길동');assert.equal(await page.locator('#signature').inputValue(),'홍길동');
 await page.locator('#backInfo').click();await page.locator('#name').fill('김길동');await page.locator('#goConsent').click();await page.locator('#applySubmitButton').click();assert(alerts.at(-1).includes('이름과 같아야'));await page.locator('#signature').fill('김길동');await page.locator('#applySubmitButton').click();
 await frame.locator('h1').waitFor();assert.equal(await frame.locator('[name="answer_rank"]').nth(0).inputValue(),'A');assert(await frame.locator('[name="answer_checks"][value="나"]').isChecked());
 fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});await page.screenshot({path:path.join(root,'artifacts/v94-survey-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'artifacts/v94-survey-mobile.png'),fullPage:true});
 assert.equal(await frame.locator('body').evaluate(b=>b.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1280,height:900});
 await page.evaluate(()=>{document.querySelector('#nurimSurveyDialog').close();window.incheonSupabase.auth.getSession=async()=>({data:{session:{user:{id:'manager-a'},access_token:'test-only-token'}}});saveSession({role:'manager',name:'A',accountId:'manager-a',centerName:'기관 A'});applyAdminAccess();document.querySelector('#adminDialog').showModal();});
 await page.locator('[data-tab="surveyManage"]').click();
 const editor=page.locator('#surveyManage');await editor.locator('[data-action="new"]').click();await editor.locator('[data-action="add"]').click();
 await editor.locator('[data-field="type"]').selectOption('rank');await editor.locator('[data-action="addOption"]').click();await editor.locator('[data-action="addOption"]').click();
 await editor.locator('textarea[data-option="0"]').fill('A');await editor.locator('textarea[data-option="1"]').fill('B');await editor.locator('textarea[data-option="2"]').fill('C');await editor.locator('[data-field="rankCount"]').selectOption('2');
 await editor.locator('[data-action="preview"]').click();await frame.locator('h1').waitFor();assert.equal(await frame.locator('fieldset:not(.basic) select').count(),2);await page.locator('#nurimSurveyDialog > .dialogTitle button').click();
 await editor.locator('[data-field="type"]').selectOption('checkbox');await editor.locator('[data-field="selectionMode"]').selectOption('exact');await editor.locator('[data-field="selectionCount"]').fill('2');await editor.locator('[data-action="preview"]').click();await frame.locator('h1').waitFor();assert.equal(await frame.locator('.selectionHint').innerText(),'2개를 선택해 주세요.');
 console.log(JSON.stringify({passed:'institution reset/switch, disability combinations, signature blocking, rank count, exact checkbox validation, back navigation and answer preservation, mobile overflow, builder rank/checkbox configuration preview',pageErrors:errors,alerts}));assert.deepEqual(errors,[]);
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
